import type { Metadata } from "next";
import LocaleSwitcher from "@/components/LocaleSwitcher";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <LocaleSwitcher />
      {children}
    </>
  );
}
